# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Goldfinch"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Mininal theme with colors based on the beautiful Goldfinch"
homepage = "https://fabious.github.io/"
tags = []
features = []
min_version = "0.1.0"

[author]
  name = "Fabious"
  homepage = "https://github.com/fabious"
